Fix sizes for 32 bit Windows
 ## Problem

The following errors were being received:

```
error[E0512]: transmute called with types of different sizes
    --> ruby-structs\src\ruby_2_3_8.rs:1266:18
     |
1266 |         unsafe { ::std::mem::transmute(self._bitfield_1.get(1usize, 63u8) as u64) }
     |                  ^^^^^^^^^^^^^^^^^^^^^
     |
     = note: source type: u64 (64 bits)
     = note: target type: u32 (32 bits)
error[E0512]: transmute called with types of different sizes
    --> ruby-structs\src\ruby_2_3_8.rs:1271:28
     |
1271 |             let val: u64 = ::std::mem::transmute(val);
     |                            ^^^^^^^^^^^^^^^^^^^^^
     |
     = note: source type: u32 (32 bits)
     = note: target type: u64 (64 bits)
error[E0512]: transmute called with types of different sizes
    --> ruby-structs\src\ruby_2_3_8.rs:1287:45
     |
1287 |             let num_entries: u64 = unsafe { ::std::mem::transmute(num_entries) };
     |                                             ^^^^^^^^^^^^^^^^^^^^^
     |
     = note: source type: u32 (32 bits)
     = note: target type: u64 (64 bits)
error: aborting due to 3 previous errors
```

 ## Solution

It looks like in the past, this issue has been seen and resolved, since
I found commit d8b2f788e1e151267eadf9a582d871d674d58d24.

I made the changes found there by changing `u64` to `usize`.

I also changed other fields that were `::std::os::raw::c_ulong` in the 3
files to be `usize`, which is consistent with all of the other
ruby-struct files. I'm not sure why those one specifically have
`::std::os::raw::c_ulong`, but given that those 3 we added with the
parent PR, and they versions are spread out, I think the fields being
`::std::os::raw::c_ulong` is more of a side effect than a necessicity.
That's my long winded way of saying: I don't think changing these to
`usize` should have a negative affect.